### PR TITLE
Update documentation

### PR DESCRIPTION
**Pull request by cardosolucas**
Changed:

- 'marvin test' to 'marvin';
- Vagrant documentation removed;
- Some broken links were fixed.

### CODE REVIEW

**Review by Wei-1 — COMMENTED** [review]
LGTM
Is there a reason why we remove the Vagrant section?

**Comment by cardosolucas** [comment]
I removed because I didn't find it in the Apache official repo, but we can rollback this change if its still used.

**Comment by Wei-1** [comment]
I think it is left empty for the future.
I agree that removing them will make the website more professional.
@oldfly what do you think?

**Comment by oldfly** [comment]
@Wei-1 Yes, the Vagrant part should be deleted, its for Windows user, and we got Docker now

**Comment by Wei-1** [comment]
Cool, I will merge this PR this weekend.

**Pull request merged**
